version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws --version
    - $(aws ecr get-login --region us-east-1 --no-include-email)
    
  build:
    commands:
    - echo Build started on `date`
    - echo Building Java
    - cd pms-pention-dis-rep
    - mvn compile
    - mvn package -DskipTests
    - echo Building the docker image..
    - docker docker build -t pms-pention-dis-rep .
    - docker tag pms-pention-dis-rep:latest 156962844638.dkr.ecr.us-east-1.amazonaws.com/pms-pention-dis-rep:latest
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing docker image
    - docker push 156962844638.dkr.ecr.us-east-1.amazonaws.com/pms-pention-dis-rep:latest
    - echo Writting definition file
    - printf '[{"name":"pms-pention-dis-rep","imageUri":"%s"}]' 156962844638.dkr.ecr.us-east-1.amazonaws.com/pms-pention-dis-rep:latest > imagedefinitions.json
artifacts:
  files:
  - pms-pention-dis-rep/imagedefinitions.json